name: Python CI - format using "ruff", then analyse using "Pylint"

on:
  push:
    branches: [main]
    paths:
      - '**/*.py'          # run on pushes that modify any .py file
  pull_request:
    branches: [main]
    paths:
      - '**/*.py'          # run on pulls that modify any .py file

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    strategy:
      matrix:
        python-version: ["3.14"]
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip packages
        id: pip-cache
        uses: actions/cache@v5
        with:
        # Cache key includes OS, Python version, and a hash of the lock file
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements_ci.txt') }}
        # Restore from any previous cache with the same OS and Python version
          restore-keys: |
            ${{ runner.os }}-pip-
        # Directories to cache (default pip cache location)
          path: |
            ~/.cache/pip
      - name: Upgrade and install dependencies for Python CI
        # if: steps.pip-cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest pytest-cov ruff
          if [ -f requirements_ci.txt ]; then pip install -r requirements_ci.txt; fi
      #- name: Format with Black
        #run: |
          #python -m black .
          #python -m black --check .
      #- name: Sort imports for Python files using isort
        #run: |
          # isort **/*.py --settings-path ./.isort.cfg
      - name: Lint and Format using Ruff
        run: |
          python -m ruff format *.py
      #- name: Lint with Flake8
        #run: |
          #python -m flake8 . --count --show-source --statistics --max-line-length=200
      - name: Analyse code using pylint
        run: |
          python -m pylint --disable=duplicate-code $(git ls-files '*.py')

# OLD:
# python -m pip install --upgrade pip
# pip install black
# pip install flake8
# pip install pylint pytest pytest-cov

# Version: 1.0.1
# Updated AEST: 2026-02-09 15:39:39 +1100

# SOURCES:
# https://github.com/actions/cache
# https://github.com/actions/checkout
# https://github.com/actions/setup-python
# https://github.com/astral-sh/ruff
# https://pypi.org/project/isort/
# https://pypi.org/project/ruff/
